config/routes.rb
Rails.application.routes.draw do
  
  get 'todos/:id/complete', to:'todos#complete', as: 'todos_complete'
  get 'todos/list', to: 'todos#list', as: 'list_todos'
  get 'todos', to: 'todos#index'
  post 'todos', to: 'todos#create'
  get 'todos/new', to: 'todos#new', as: 'new_todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  get 'todos/:id', to: 'todos#show', as:'todo'
  patch 'todos/:id', to:'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:show, :destroy, :edit, :update, :complete]
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            flash[:notice] = "Your new ToDo was added successfully"
            redirect_to todos_path
        else
            render 'new'
        end
    end

    def show
    end

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    def edit
    end

    def update
        if @todo.update(todo_params)
            flash[:notice] = "Your new ToDo was updated successfully"
            redirect_to todo_path(@todo)
        else
            render 'edit'
        end
    end

    def complete
        if @todo.completed == false
            @todo.completed = true
            @todo.save
            flash[:notice] = "Completed! Keep it up! "
            redirect_to todos_path
        else
            @todo.completed = false
            @todo.save
            redirect_to todos_path
        end  
    end

    def list
        @todo_completed = Todo.where(completed: true)
        @todo_incompleted = Todo.where(completed: false)
    end

    private
    def set_todo
        @todo = Todo.find(params[:id])  
    end
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navigation'%>
    <%= render 'shared/messages'%>
    <div class="container pt-4">
    <%= yield %>
    </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_deck.html.erb
<div class="row row-cols-1 row-cols-md-2">
<% @todos.each do |todo| %>
  <div class="col mb-4 ">
    <div class="card">
      <div class="card-body card-bg">
        <h4 class="card-title text-light font-weight-bold"><%= todo.description %></h4>
        <% if todo.completed == true %>
        <%=link_to "COMPLETED" , todos_complete_path(todo),class:'btn btn-outline-success' %>
        <% else %>
        <%=link_to "UNFINISHED", todos_complete_path(todo),class: 'btn btn-outline-warning' %>
        <%end%>
        <hr id="card-line">
        <%= link_to "Edit", edit_todo_path(todo), class: "btn btn-warning" %>
        <%= link_to "Show", todo_path(todo), class: "btn btn-success" %>
        <%= link_to "Delete", todo_path(todo), class:"btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_errors.html.erb
<% if @todo.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(@todo.errors.count, "error") %>
  prohibited this ToDo from being saved:
  </h4>
  <hr>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/shared/_form.html.erb
<%= render 'shared/errors' %>
<div class='row'>
 <div class="col-md-6 offset-md-3">
<%= form_with(model: @todo, local: true ) do |f| %>
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class:'form-control' %>
  </div>
  <div class="form-check pb-3">
  <%= f.check_box :completed, class:'form-check-input' %>
  <%= f.label :completed, class:'form-check-label', for:'completed' %>
  </div>
  <%= f.submit class: 'btn btn-info' %>
<% end %>
  <div class="center">
    [ <%= link_to "Back to Todos listing", root_path %> ]
  </div>
  </div>
</div>

app/views/shared/_messages.html.erb
<div class="center container pt-2">
    <% flash.each do |name, msg| %>
    <div class="alert alert-success" role="alert">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
    </div>
        <% end %>
    </div>
</div>

 

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-fixed-top" style="background-color: #000000;">
 <div class="container">
  <%= link_to "ToDos App", root_path, class:"navbar-brand", id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active pr-4 font-weight-bold">
        <%= link_to "List", list_todos_path, class: "nav-link"%>
      </li>
      <li class="nav-item active font-weight-bold">
        <%= link_to "New ToDo", new_todo_path, class: "nav-link"%>
      </li>
    </ul>
  </div>
 </div>
</nav>

app/views/todos/edit.html.erb
<h1 class="text-center">Edit ToDo!</h1>

<%= render 'shared/form'%>

app/views/todos/index.html.erb
<h1 class="font-weight-bold pb-3">ToDos List</h1>

<%= render 'shared/deck' %>

app/views/todos/list.html.erb
<h1 class="font-weight-bold pb-3">ToDos List</h1>

<div class="row">
  <div class="col-sm-6">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">ToDo</th>
          <th scope="col">Status</th>
          <th scope="col">Date</th>
        </tr>
      </thead>

      <% @todo_incompleted.each do | todo | %>
      <tbody>
        <tr>
          <td><%= todo.description %></td>
          <td>Incompleted</td>
          <th scope="row"><%= todo.created_at %></th>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="col-sm-6">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">ToDo</th>
          <th scope="col">Status</th>
          <th scope="col">Date</th>
        </tr>
      </thead>

      <% @todo_completed.each do | todo | %>
      <tbody>
        <tr>
          <td><%= todo.description %></td>
          <td>Completed</td>
          <th scope="row"><%= todo.created_at %></th>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/todos/new.html.erb
<h1 class="text-center font-weight-bold pb-3">Add a new Todo!</h1>

<%= render 'shared/form'%>

app/views/todos/show.html.erb
<div class="blog-post">
        <h2 class="blog-post-title font-weight-bold"><%= @todo.description %></h2>
        <p class="blog-post-meta font-weight-bolder">Added at: <%= @todo.created_at %></p>
        <hr>
        <% if @todo.completed == true %>
        <%=link_to "COMPLETED", todos_complete_path(@todo), class:'btn btn-outline-success' %>
        <% else %>
        <%=link_to "UNFINISHED", todos_complete_path(@todo), class:'btn btn-outline-warning' %>
        <%end%>
        <div class="center">
          [ <%= link_to "Back to Todos listing", root_path %> ]
        </div>
</div>